[theme]
base = "light"
primaryColor = "#2696D2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#222222"
font = "sans serif"

[server]
# Disables the local file watcher.
fileWatcherType = "none"

# Server configuration
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
